Add button to export submissions data as a CSV file
rhomeister/alphagrader pull request #417
Opened 2022-04-13 15:41 UTC by carlosahs

The button is added next to the rerun submissions button:

![image](https://user-images.githubusercontent.com/52082645/163217845-7d3f833b-3264-4cd6-a640-1316c011cc2f.png)

Once clicked, a CSV file will be downloaded. The header of the CSV file contains the following attributes:
```ruby
attributes = %w[id uploaded_by_id created_at updated_at test_results_count successful_test_results_count language status]
```

2022-04-18 12:56 UTC, carlosahs reviewed
Includes `ActiveSupport::Testing::TimeHelpers`, otherwise it is reported as an uninitialized constant.

2022-04-21 20:34 UTC, rhomeister requested changes
2 small comments. Ready to go!

2022-04-21 20:34 UTC, rhomeister commented on app/views/submissions/index.haml
> +-# -# reload page every 2s if submissions are still running
cleaner to keep this here, and remove from line 16, unless you have a good reason to do so

2022-04-21 20:34 UTC, rhomeister commented on config/routes.rb
> +    # get 'submissions/export', to: 'submissions#export'
remove

2022-07-13 01:58 UTC, merged